parameters:
#    niko_guitar.example.class: Niko\GuitarBundle\Example

services:
#    niko_guitar.example:
#        class: %niko_guitar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
